sudo: true

language: generic 

services:
  - docker

before_install:
  - docker build -t shubhadip/docker-react -f dev.Dockerfile .

script:
  - docker run -e CI=true shubhadip/docker-react npm run test -- --coverage